### ISSUE TITLE
Make it more "CI/travis-friendly"

### ISSUE THREAD

**Issue by seriyps** [crownedgrouse/geas_rebar3#8]
It would be nice to make it possible to configure this plugin to return non-zero return code if some configured criteria was not met. This way it will be easy to fail CI build in case when pull-request breaks some release compatibility expectations.
So, for example, rebar3 config option could be added to verify that the code is in specified release frame.
Something like

```
{geas,
  [{release_frame, {"17.0", "21.0"}}]}.
```
or
```
{geas,
  [{oldest_supported_otp, "17.0"}]}.
```

So, if code in pull-request breaks compatibility with Erlang 17, geas check will return non-zero response code and will report only those calls which break this constrain.

Maybe it can be optional feature and behave like that only when some special flag is provided in command-line

**Comment by crownedgrouse** [comment]
Hi,
I'm currently working to let erlang.mk and rebar3: 
 - -exit 1 if current version is incompatible with release window
 - exit 2 if release window do not match a required version range. 
Release frame with a semver range syntax, like " >18.3 <= 19.1 || 21.2" .
Are you OK with this ? Your opinion welcome.

**Comment by seriyps** [comment]
I was thinking about it for some time and can't really imagine any usecase other than "the oldest supported version". I mean why would someone restrict the latest supported version?

**Comment by seriyps** [comment]
But in general yep, this sounds awesome! Thanks!

**Comment by crownedgrouse** [comment]
restriction can come from a third party dependency not supporting latest version. I prefer to do generic and let user see if it is useful.
OK I will work on that (dev branch) . It would be nice to test your side once done.

**Comment by seriyps** [comment]
Yep, sure. Please, ping me in this ticket when it's time to test! Thanks!

**Comment by crownedgrouse** [comment]
some news. Unfortunately it is not possible to exit something else than 1 in rebar3, from a plugin (except by halting in plugin itself, but so crappy) . I raised a ticket at rebar3 github project.
For now I will simply work to exit 1 in case of error for rebar3, with an explicit message for different cases. For erlang.mk I can probably exit with something else than 1 only. Take you aware.

**Comment by crownedgrouse** [comment]
my semver implementation seems OK and tests running OK. Do not hold your breath, but I will try to finish this soon, to let you test.

**Comment by crownedgrouse** [comment]
By talking with Fred at rebar3, we ended to conclusion that it would be better to exit from plugin as rebar3 is not aimed to exit in all cases, and exit code meaning might be different for each plugin. Plugin documentation is the right place to describe those exit codes. So I should be able to let rebar3 and erlang.mk exit the same codes.

**Comment by crownedgrouse** [comment]
I thought that Erlang.mk would be easy, but I forgot that make does not exit with last command status, but only 2 on error, and no way to change this. rebar3 will be finally easier. But at least we can exit nonzero for both. I will need to find another way for Erlang.mk users to know what is the exact error for scripting integration

**Comment by crownedgrouse** [comment]
A little delay due to extraction of semver stuff and creation of another project https://github.com/crownedgrouse/samovar . I hope you like the project's name :) !

**Comment by seriyps** [comment]
Ahah! Thanks! Love this name a lot!

**Comment by crownedgrouse** [comment]
Hi, please see wiki API changelog at "[WIP] Release >= 2.5 dev branch" . For now only an environment variable GEAS_RANGE.  
Still working to let this available in rebar config.
You can test by using dev branch of geas_rebar3, this will use dev branch of geas too.
Still experimental . your feedback welcome.

**Comment by seriyps** [comment]
Hi, sorry, can't figure out where should I look for API changelog?

**Comment by crownedgrouse** [comment]
in geas wiki : 
https://github.com/crownedgrouse/geas/wiki/API-changelog

**Comment by seriyps** [comment]
Yep, `{geas, [{range, ">=19.2 || <21.3"}]}` syntax looks reasonable. I like it!

I also recently discovered that old rebar had `require_min_otp_vsn` config option: https://github.com/rebar/rebar/blob/master/src/rebar_require_vsn.erl and you can still [find some projects](https://github.com/search?q=require_min_otp_vsn&type=Code) that have it in their rebar.config (guess, for historical reasons). rebar3 ignores this option.
Might it make sense to pick this attribute as well?

**Comment by seriyps** [comment]
I tried to use it:
Put following to `rebar.config`:
```erlang
{plugins, [%rebar3_proper,
           {geas_rebar3, {git, "https://github.com/crownedgrouse/geas_rebar3.git", {branch, "dev"}}}
          ]}.

{geas, [{range, ">=20.0"}]}.
```

And run `DEBUG=1 rebar3 geas` but it seems it still runs the check for all the range of OTP versions and it crashed at the end:

```
<..>
./_build/test/lib/mtproto_proxy/test/prop_mtp_statefull.beam
19.0      maps:take/2

./_build/test/lib/mtproto_proxy/test/single_dc_SUITE.beam
18.0      gen_server:stop/1

./_build/test/lib/ranch/ebin/ranch.beam
17.1      maps:get/3

./_build/test/lib/ranch/ebin/ranch_acceptors_sup.beam
17.1      maps:get/3

./_build/test/lib/ranch/ebin/ranch_conns_sup.beam
17.1      maps:get/3

./_build/test/lib/ranch/ebin/ranch_listener_sup.beam
17.1      maps:get/3

./_build/test/lib/ranch/ebin/ranch_proxy_header.beam
17.1      maps:get/3

./_build/test/lib/ranch/ebin/ranch_ssl.beam
19.0      ssl:getstat/1, ssl:getstat/2
===> Unexpected geas exit code
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: badarg
===> Stack trace to the error location:
[{erlang,halt,[-1,[]],[]},
 {erlang,halt,1,[]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/prod/lib/rebar/src/rebar_core.erl"},
              {line,154}]},
 {rebar3,main,1,
         [{file,"/home/tristan/Devel/rebar3/_build/prod/lib/rebar/src/rebar3.erl"},
          {line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,759}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_em,1,[]},
 {init,do_boot,3,[]}]
```

**Comment by crownedgrouse** [comment]
But do you see compat table with versions on right side (new features)?  For now only environment variable GEAS_RANGE is working. Range in rebar3 config not implemented yet.

**Comment by crownedgrouse** [comment]
Geas collect release window for all modules and, after that, compare to range. So not abnormal for me this output, apart crash obviously

**Comment by crownedgrouse** [comment]
could you ` rm -rf ~/.cache/rebar3/plugins/geas* `  to be sure that you are using right version ? rebar3 do not upgrade always properly git plugins when a cache is existing. you should see something like 
```
$ rebar3 geas
===> Fetching geas_rebar3 (from {git,"https://github.com/crownedgrouse/geas_rebar3.git",
                       {branch,"dev"}})
===> Fetching geas (from {git,"https://github.com/crownedgrouse/geas.git",{branch,"dev"}})
===> Compiling geas
===> Compiling geas_rebar3
===> Verifying dependencies...
===> Compiling test
   R15                   22.0       Geas database                       2.5.0
---Min--------Arch-------Max----------------------------------------------------
   R16B                             cowboy                              1.0.4
                         19.3       cowlib                              1.0.0
                                    ranch                               1.0.0
   R16B       x86        18.1       test                                0.0.1
--------------------------------------------------------------------------------
   R16B       x86        18.1       Global project                      0.0.1

C : 22.0
R :  22.0.1 22.0.2 22.0.3 22.0.4 22.0.5 22.0.6
T : R16B R16B01 R16B02 R16B03 R16B03-1 17.0 17.1 17.3 17.4 17.5 18.0 18.1

./_build/default/lib/cowboy/ebin/cowboy_clock.beam
R16B      erlang:integer_to_binary/1

./_build/default/lib/cowboy/ebin/cowboy_req.beam
R16B      erlang:integer_to_binary/1

./_build/default/lib/cowboy/ebin/cowboy_static.beam
R16B      erlang:integer_to_binary/1

./_build/default/lib/cowboy/ebin/cowboy_websocket.beam
R15B02    crypto:hash/2

./_build/default/lib/cowlib/ebin/cow_multipart.beam
19.3      crypto:rand_bytes/1

./_build/default/lib/test/ebin/test.beam
R16B      erlang:binary_to_integer/1

18.1      ssh_message:encode_host_key/1
===> Current version is incompatible with release window
$ echo $?
1
```

**Comment by crownedgrouse** [comment]
if still in issue, please tell me your rebar version

**Comment by seriyps** [comment]
Geas da76d8c970593584b29d5f07e2b72963b1d2e23a
geas_rebar3 da76d8c970593584b29d5f07e2b72963b1d2e23a

Application: https://github.com/seriyps/mtproto_proxy

rebar.config:
```
<..>
{plugins, [
    {geas_rebar3, {git, "https://github.com/crownedgrouse/geas_rebar3.git", {branch, "dev"}}}]
}.
<..>
```

command

```
$ GEAS_RANGE=">20.0" rebar3 geas
===> Compiling rebar3_bench
===> Verifying dependencies...
===> Compiling mtproto_proxy
R15                   22.0       Geas database                       2.5.0
---Min--------Arch-------Max----------------------------------------------------
17.1                             eministat                          0.10.1
erlang_psq                          1.0.0
goldrush                            0.1.9
hut                                 1.3.0
17.0                             lager                               3.6.3
20.0                             mtproto_proxy                       0.6.1
19.0                             ranch                               1.7.0
geas_rebar3                         1.1.0
rebar3_proper                      0.11.1
--------------------------------------------------------------------------------
20.0                  22.0       Global project                      0.6.1

C : 21.2.6
L : 20.0 20.1 20.2 20.3 21.0 21.1 21.2 22.0

./_build/default/lib/eministat/ebin/eministat_plot.beam
17.1      maps:get/3

./_build/default/lib/lager/ebin/error_logger_lager_h.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager.beam
R16B01    lists:filtermap/2

./_build/default/lib/lager/ebin/lager_app.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_stdlib.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_sup.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_trunc_io.beam
17.0      erlang:map_size/1

./_build/default/lib/mtproto_proxy/ebin/gen_timeout.beam
18.0      erlang:convert_time_unit/3, erlang:system_time/1

./_build/default/lib/mtproto_proxy/ebin/mtp_aes_cbc.beam
R16B01    crypto:block_decrypt/4, crypto:block_encrypt/4, crypto:next_iv/2

./_build/default/lib/mtproto_proxy/ebin/mtp_config.beam
20.0      string:lexemes/2, string:split/3, string:trim/3

./_build/default/lib/mtproto_proxy/ebin/mtp_dc_pool.beam
19.0      maps:take/2

./_build/default/lib/mtproto_proxy/ebin/mtp_down_conn.beam
19.0      maps:take/2

./_build/default/lib/mtproto_proxy/ebin/mtp_fake_tls.beam
R16B      crypto:hmac/3

./_build/default/lib/mtproto_proxy/ebin/mtp_handler.beam
18.0      erlang:convert_time_unit/3, erlang:system_time/1

./_build/default/lib/mtproto_proxy/ebin/mtp_intermediate.beam
17.1      maps:get/3

./_build/default/lib/mtproto_proxy/ebin/mtp_metric.beam
18.0      erlang:monotonic_time/0

./_build/default/lib/mtproto_proxy/ebin/mtp_obfuscated.beam
R16B01    crypto:stream_encrypt/2, crypto:stream_init/3

./_build/default/lib/mtproto_proxy/ebin/mtp_policy.beam
20.0      string:casefold/1

./_build/default/lib/mtproto_proxy/ebin/mtp_policy_counter.beam
18.0      ets:update_counter/4

./_build/default/lib/mtproto_proxy/ebin/mtp_policy_table.beam
18.0      erlang:system_time/1

./_build/default/lib/mtproto_proxy/ebin/mtp_session_storage.beam
18.0      erlang:system_time/1, ets:update_counter/4

./_build/default/lib/mtproto_proxy/ebin/mtproto_proxy_app.beam
19.0      lists:join/2

./_build/default/lib/ranch/ebin/ranch.beam
17.1      maps:get/3

./_build/default/lib/ranch/ebin/ranch_acceptors_sup.beam
17.1      maps:get/3

./_build/default/lib/ranch/ebin/ranch_conns_sup.beam
17.1      maps:get/3

./_build/default/lib/ranch/ebin/ranch_listener_sup.beam
17.1      maps:get/3

./_build/default/lib/ranch/ebin/ranch_proxy_header.beam
17.1      maps:get/3

./_build/default/lib/ranch/ebin/ranch_ssl.beam
19.0      ssl:getstat/1, ssl:getstat/2
===> Release window do not match required semver version range
```

```
rebar 3.9.0 on Erlang/OTP 21 Erts 10.2.4
```

Well, it now says that release window do not match, but AFAIK, my release should support 20+. Or I'm missing something?

My expectation is that it checks if my release's window is inside the specified range. Or does it checks that it's exactly the specified range?

**Comment by seriyps** [comment]
Did I get it correctly, that if I set `GEAS_RANGE=">20.0"` it means that my release should be compatible with erlang 20+? So, if someone's PR will break compatibility with erlang 19 - it's ok, but if it breaks compatibility with 20 or 21 or 22 - it's an error?

**Comment by crownedgrouse** [comment]
Thanks, I will check. Indeed it should allow version inside a larger range. I will use you project for testing.

**Comment by crownedgrouse** [comment]
But I just see that a function is needing 20.0. So your range should be >=20.0.and not >20.0.?

**Comment by seriyps** [comment]
It's even stranger with `>=`:

* `GEAS_RANGE=">=22.0"` - error
* `GEAS_RANGE=">=21.0"` - error
* `GEAS_RANGE=">=20.0"` - success
* `GEAS_RANGE=">=19.0"` - success
* `GEAS_RANGE=">=18.0"` - success

**Comment by crownedgrouse** [comment]
no, from my point of view it is OK .
As your project need at least 20.0 to work, >=18.0, >=19.0 and >=20.0 match the requirement.
if you require the project to run with >=21.0, this does not match as currently 20.0 is required.
are you ok with this ?

**Comment by seriyps** [comment]
Well, how I feel about this config is:

```
+ - it's ok to NOT work on those releases
X - it should work on those releases

All erl releases:
18 -- 19 -- 20 -- 21 -- 22 --> ∞

{range, ">=20.0"} (app shouldwork on OTP 20+):
|+++++|+++++|xxxxxxxxxxxxxxxxxxxxxx

{range, ">20.0"} (app should work on OTP AFTER 20.0):
|+++++|+++++|++xxxxxxxxxxxxxxxxxxxx

{range, "<20"} (app is not compatible with erl 20+; it will not work on 20+ so you can't introduce calls to 20+ APIs)
|XXXXX|XXXXX|++++++++++++++++++++++

{range, "<=20"} (app is not compatible with OTP AFTER 20.0. You can't use APIs introduced after 20.0):
|XXXXX|XXXXX|XX++++++++++++++++++++

{range, "19 - 20"} (app should work on OTP from 19 to 20.3, not guaranteed to work on 21+ and before 19):

|+++++|XXXXX|XXXXX|+++++++++++++++++
```

**Comment by crownedgrouse** [comment]
OK so I think this is only a misunderstanding.
What you need can be described with ^ and ~ semver syntax. 
For instance : 
 ^20.0     is >=20.0.0 <21.0.0 	
 ~20.1     is >=20.1.0 <20.2.0 	
 ^20       is >=20.0.0 <21.0.0 	 
 ~20       is >=20.0.0 <20.0.0 

so for your cases you mention above , respectively : 
(app shouldwork on OTP 20+; it uses APIs introduced in OTP20, not uses APIs introduced in 21 or 22+)   => ^20

(app should work on OTP AFTER 20.0; it uses APIs introduced in 20.1) => ^20.0

(app is not compatible with erl 20+; it will not work on 20+ so you can't introduce calls to 20+ APIs) => <20 

(app is not compatible with OTP AFTER 20.0. You can't use APIs introduced after 20.0) => <=20 ^20.0

(app should work on OTP from 19 to 20.3, not guaranteed to work on 21+ and before 19) => >19 <=20.3

Are you ok ?

**Comment by crownedgrouse** [comment]
hi, by reading again this thread, I found that `{geas, [{range, ">=19.2 || <21.3"}]}` was absurd, because always true. Real range in this case should use "and" statement, i.e `{geas, [{range, ">=19.2 <21.3"}]}` .  Using "or" statement  should describe a splitted range with no common range, like `<=19.3 || >= 21` , to exclude 20 releases.

**Comment by seriyps** [comment]
Ah.. Ok. I'm not that familiar with semver. So, as long as `range` contains a valid semver range and this range means the range of OTP versions where this app is guaranteed to work (in terms of OTP API use) - I'm ok.

**Comment by crownedgrouse** [comment]
I will try to let `range` working in rebar.config for 2.5.  it will be better for you. I do not forget your post about `require_min_otp_vsn` .  If you could continue test, now you understand the semver syntax...

**Comment by crownedgrouse** [comment]
note that `samovar` understand `20.x`  or `20.*`  syntax as well , if ~or ^is not handy for you.

**Comment by crownedgrouse** [comment]
rebar3 's `minimum_otp_vsn` cannot be used as rebar3 simply exit with error if a lower release is use to compile project. At this point, geas is not launched.

**Comment by crownedgrouse** [comment]
did you test  and is it satisfying ? wanting to prepare merge and publish for the next OTP release ...

**Comment by seriyps** [comment]
Ah, sorry, not yet. Will try bit later today or tomorrow.

**Comment by crownedgrouse** [comment]
No worries. Kind of you to be beta tester...

**Comment by crownedgrouse** [comment]
Any feedback?

**Comment by crownedgrouse** [comment]
Hi @seriyps  . I want to merge those new features for my release for newly release 22.2 .
if you have any issue to raise or comment, you are welcome.

**Comment by crownedgrouse** [comment]
Hi, see last geas version 2.6.1 and geas_rebar3 plugin 1.3.1 . variables can be set in `rebar.config` and a new 'frame' feature for semver check. Hope you will enjoy ! thanks for the heads up . closing !
