### ISSUE TITLE
GEAS to report on invalid `minimum_otp_vsn` if in rebar3 project

### ISSUE THREAD

**Issue by kivra-pauoli** [crownedgrouse/geas_rebar3#9]
Would you be interested in having `geas` report on an incorrect `minimum_otp_vsn` in the scope of a `rebar3` project?

What could be done?

* get that config. key from `rebar.config`
* compare to `geas`' calculated release window
* potentially report an error

## Motivation

When I saw `===> Current Erlang/OTP release is incompatible with project release window` I thought this was what `geas` was complaining about, but after I commented out that option in `rebar.config` I understood "Current Erlang/OTP release" is "The Erlang/OTP release used for the analysis".

Maybe we could add the calculated release value to the error message?

**Comment by crownedgrouse** [comment]
Sorry I transferred the issue here, but was closed, reopening it.

**Comment by kivra-pauoli** [comment]
I'm not exactly sure how to recover the analysis state from `geas`, in the plugin.

My goal with this change would be:

1. get the Max. reported by `geas`
2. get `minimum_otp_vsn` from `rebar.config`
3. if 2. < 1. then there _might_ be a problem

I write _might_ because the `geas` database might be outdated (e.g. 26.1, vs. 26.2 - even though I think this'll be least-concern) so it'd just be a warning, not an error.

**Comment by kivra-pauoli** [comment]
Otoh, since compilation is mostly always required, and the minimum OTP version is already checked by `rebar3`, it seems this'd only be useful in a handful of cases. I'm closing this, for now, and if it makes sense I'll return to it in the future. Thanks.
